### ISSUE TITLE
Test stürzt ab durch Parallelisierung

### ISSUE THREAD

**Issue by friedensfurz** [I-Al-Istannen/SimpleCodeTester#3]
Hey, mir ist aufgefallen, dass der Codetester komische Fehler ausgibt, wenn auf einen Java 8 Stream .parallel() aufgerufen wird.

Hier ein Auszug aus dem Fehlerbericht:
`ExceptionInInitializerErrorjava.lang.ExceptionInInitializerError	at java.base/java.util.concurrent.ForkJoinPool$InnocuousForkJoinWorkerThreadFactory$1.run(ForkJoinPool.java:3227)	at java.base/java.util.concurrent.ForkJoinPool$InnocuousForkJoinWorkerThreadFactory$1.run(ForkJoinPool.java:3225)	at java.base/java.security.AccessController.doPrivileged(Native Method)	at java.base/java.util.concurrent.ForkJoinPool$InnocuousForkJoinWorkerThreadFactory.newThread(ForkJoinPool.java:3224)	at java.base/java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1328)	at java.base/java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1352)	at java.base/java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1476)	at java.base/java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:1903)	at java.base/java.util.concurrent.ForkJoinTask.fork(ForkJoinTask.java:704)	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:324)	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)`

Wäre cool, wenn du mal drüberschauen könntest,
LG Paul

**Comment by I-Al-Istannen** [comment]
Hey, vielen Dank :)

Die CI ist durch (https://ci.ialistannen.de/job/SimpleCodeTester/), es sollte jetzt gehen. Wenn nicht, mache die issue hier grad wieder auf :)

Schöne Nacht noch ;)
