### ISSUE TITLE
command called for the x time creates AccessControlException access denied ("java.lang.RuntimePermission" "createClassLoader")

### ISSUE THREAD

**Issue by joergister** [I-Al-Istannen/SimpleCodeTester#8]
I have a problem with your online code tester, since just copyin all the input and paste it locally on my machine (Oracle JDK 14, no modification made) doesn't result in an AccessControlException access denied ("java.lang.RuntimePermission" "createClassLoader"), whereas in your tester it does.
Funny thing is: the command is called several times before in this test, even with the exact same arguments. Therefore if the code really needs to have the permission "createClassLoader" then it should have failed earlier on and not fail at the x call of the command.

Full error message: 

```
Expected 'C;23'
AccessControlException
access denied ("java.lang.RuntimePermission" "createClassLoader")
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "createClassLoader")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at me.ialistannen.simplecodetester.execution.slave.SubmissionSecurityManager.checkPermission(SubmissionSecurityManager.java:57)
	at java.base/java.lang.SecurityManager.checkCreateClassLoader(SecurityManager.java:384)
	at java.base/java.lang.ClassLoader.checkCreateClassLoader(ClassLoader.java:369)
	at java.base/java.lang.ClassLoader.checkCreateClassLoader(ClassLoader.java:359)
	at java.base/java.lang.ClassLoader.<init>(ClassLoader.java:456)
```
Expected behaviour would be to just work since it does so on my local machine.

If this helps for debugging I will give you a copy of my code, problem is, its in a private repo so collaborators have write access, therefore I would prefer hand over a link to a zip or something like this. Open for better ideas.

**Comment by I-Al-Istannen** [comment]
It looks like *something* in your code triggers a request for a new class loader. I'll probably have to have a look at it, you could send me an email to `ialistannen<<<at>>>posteo.de` without the angle brackets or `at`. I am also in the KIT Math/Info Discord, if you are in there as well.

If you are not creating your own classloader, it might be some internal JDK method that does...

**Comment by joergister** [comment]
just send you a zip.

**Comment by I-Al-Istannen** [comment]
Reflection is naughty ;)
Apparently the JDK optimizes reflective constructor invocations by generating bytecode for it *and loading it with a new classloader*.

I have whitelisted *that* code, but reflection is still severely limited for security reasons and some other things might not work as well. Your ZIP is now runnable in its current form though :)

**Comment by joergister** [comment]
Very nice. Thanks a lot for the quick response an taking action.
